### ISSUE TITLE
Publish on the NPM registry

### ISSUE THREAD

**Issue by arthur-kashaiev-ssa-group** [ssagroup/ui-kit#18]
Publish the following project on the NPM registry:

- Core
- Utils
- Hooks
- Widgets

**Comment by react-developer-ssa-group** [comment]
As I see, they're already published:

- [Core](https://www.npmjs.com/package/@ssa-ui-kit/core)
- [Widgets](https://www.npmjs.com/package/@ssa-ui-kit/widgets)
- [Hooks](https://www.npmjs.com/package/@ssa-ui-kit/hooks)
- [Utils](https://www.npmjs.com/package/@ssa-ui-kit/utils)
