### ISSUE TITLE
Responsive Image - please add a real image to improve UX

### ISSUE THREAD

**Issue by dmytrokuklenko** [ssagroup/ui-kit#208]
Currently, the utility displays a dummy image

![image](https://github.com/user-attachments/assets/2b4efc0b-7015-496f-b1ee-bab6e56e6f9f)

Please add a real image, i.e. UI Kit logo, to improve UX

**Comment by react-developer-ssa-group** [comment]
https://uikit.ssa.group/?path=/story/@ssa-ui-kit/core_utility-responsiveimage--default
