### ISSUE TITLE
Add missing tests for Badge, WithLink components 

### ISSUE THREAD

**Issue by dmytrokuklenko** [ssagroup/ui-kit#281]

**Comment by vadym-korzh-ssa-group** [comment]
Added necessary tests. Attaching test results:

![Screenshot 2024-12-05 133515](https://github.com/user-attachments/assets/ef47871d-f06c-4860-953e-16193753a334)
![Screenshot 2024-12-05 133753](https://github.com/user-attachments/assets/037b9774-03b5-4e8b-a7e1-ea5f6875ff7a)
![Screenshot 2024-12-05 133929](https://github.com/user-attachments/assets/0c26d961-9030-4d04-8108-b858ab05f1c3)
![Screenshot 2024-12-05 133717](https://github.com/user-attachments/assets/220c9615-5f27-488e-b29e-8703183eac4f)

**Comment by vadym-korzh-ssa-group** [comment]
Last batch of tests for Button resulted on 100% coverage:

![image](https://github.com/user-attachments/assets/8d044e6a-fc41-4fc4-81d6-84e58e8379ba)

**Comment by vadym-korzh-ssa-group** [comment]
Tests update for Badge:

![image](https://github.com/user-attachments/assets/415533da-da72-49b9-8c02-151409b688e5)
