### ISSUE TITLE
Implement a Badge component that can be added to another components

### ISSUE THREAD

**Issue by arthur-kashaiev-ssa-group** [ssagroup/ui-kit#58]
![Image](https://github.com/ssagroup/ui-kit/assets/82376677/bca38660-9156-4178-8732-d49359a50763)

![Image](https://github.com/ssagroup/ui-kit/assets/82376677/07f7f635-f140-4c67-bddd-e3e626319d6d)

**Comment by vitalii-ilchenko-ssa-group** [comment]
Implemented in #58
